### ISSUE TITLE
Tener ambientes de desarrollo funcionales

### ISSUE THREAD

**Issue by Henrrypg** [KellyZapata/MinTicVehiculosTrasnsporte#19]
Cada miembro del equipo debe tener instalado el entorno y herramientas requeridas para le desarollo del proyecto.

### Criterios de aceptación

- Cada miembro del equipo debe enviar capturas de pantalla de Azure DataStudio y la aplicación dotnet instalada.

**Comment by Lincunia** [comment]
![Image](https://user-images.githubusercontent.com/111134123/189462433-9e6320d5-8153-4df4-b5c0-1847d50b3460.png)
![Image](https://user-images.githubusercontent.com/111134123/189462432-6b5616d8-71ce-4527-b3e5-9b46fe1773d6.png)

Lo sé, ya debí haber hecho esto hace 2 semanas pero es que estaba intentando llevar a cabo las actividades de mi colegio.
